name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test1111
      id: test1111
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test1111
        setup-command: ''
        command: mvn test
        timeout: 50
        max-score: 11
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST1111_RESULTS: "${{steps.test1111.outputs.result}}"
      with:
        runners: test1111
